import os
import datetime
from pathlib import Path

class SessionLogger:
    def __init__(self, log_dir="logs/sessions"):
        """
        Initialize the session logger.
        
        Args:
            log_dir (str): Directory where session logs will be stored.
        """
        self.log_dir = Path(log_dir)
        self.log_dir.mkdir(parents=True, exist_ok=True)
        
        # Create a unique filename for this session
        timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        self.current_log_file = self.log_dir / f"broadcast_{timestamp}.log"
        
        self._write_header()

    def _write_header(self):
        """Write session start header."""
        with open(self.current_log_file, "a", encoding="utf-8") as f:
            f.write("="*50 + "\n")
            f.write(f"Session Started: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
            f.write("="*50 + "\n\n")

    def log_commentary(self, text: str):
        """
        Log the commentary (TTS output).
        
        Args:
            text (str): The text generated by the AI model.
        """
        timestamp = datetime.datetime.now().strftime("[%H:%M:%S]")
        log_entry = f"{timestamp} [COMMENTARY] {text}\n"
        
        with open(self.current_log_file, "a", encoding="utf-8") as f:
            f.write(log_entry)
            
    def log_system(self, level: str, message: str):
        """
        Log system events (Terminal logs).
        
        Args:
            level (str): INFO, WARNING, ERROR, etc.
            message (str): The message to log.
        """
        timestamp = datetime.datetime.now().strftime("[%H:%M:%S]")
        log_entry = f"{timestamp} [{level}] {message}\n"
        
        with open(self.current_log_file, "a", encoding="utf-8") as f:
            f.write(log_entry)

    def get_log_path(self):
        return str(self.current_log_file)
